### ISSUE TITLE
关于团队公用箱子

### ISSUE THREAD

**Issue by xiaohuihui1022** [WindLeaf233/BlockRacing#1]
我想的是能不能在主类里新建两个inventory，并设置成public static。
```Java
// Main.java
public static Inventory team1 = Bukkit.createInventory(null, 54, "team1");
public static Inventory team2 = Bukkit.createInventory(null, 54, "team2");
```
然后再在玩家按下组合键打开GUI的时候直接给玩家显示主类里那个inventory
```Java
player.openInventory(Main.team1);
```
这样一个team里的玩家就能打开同一个inventory。
并且可以还原视频里的效果qwq

**Comment by xiaohuihui1022** [comment]
刚刚双开MC试了一下，可以还原视频里的效果qwq

**Comment by FoliageOwO** [comment]
不行，我试过了。

首先，这个 `Inventory` 就不能进行存储操作，也就是只能读不能写，否则物品会直接消失。

其次，`玩家 1` 对 `Inventory` 进行的操作（拿取）不会同步到 `玩家 2`，即使是同一个 `Inventory` 对象。

所以这个需求没有想象中的那么简单。

**Comment by xiaohuihui1022** [comment]
emmmm，但是我中午的时候写了个插件试了试，本地双开mc，然后玩家1和2都打开team1的inventory，然后玩家1往里面放了一组草方块，玩家2也会被同步，玩家2也可以把他拿出来，或者他们都关掉gui，下次打开的时候草方块还在
